#!/bin/bash
#SBATCH --partition       h3c
#SBATCH --time            12:00:00
#SBATCH --nodes           1
#SBATCH --ntasks-per-node 48
#SBATCH --cpus-per-task   1
#SBATCH --error           out_%j.err
#SBATCH --output          out_%j.log

ulimit -s unlimited

module load vasp/5.4.4
#module load vasp/5.4.4_soc
# module load vasp/6.1.0
#module load vasp/6.1.0_omp
#module load vasp/6.1.0_constr_z
#module load vasp/6.1.0_optcell   # see http://blog.wangruixing.cn/2019/05/05/constr for usage

echo "============================================================"
module list
env | grep "MKLROOT="
echo "============================================================"
echo "Job ID: $SLURM_JOB_NAME"
echo "Job name: $SLURM_JOB_NAME"
echo "Number of nodes: $SLURM_JOB_NUM_NODES"
echo "Number of processors: $SLURM_NTASKS"
echo "Task is running on the following nodes:"
echo $SLURM_JOB_NODELIST
echo "OMP_NUM_THREADS = $SLURM_CPUS_PER_TASK"
echo "============================================================"
echo

srun vasp_std
#srun vasp_gam
#srun vasp_ncl
